### ISSUE TITLE
ValueError: time data 'EST' does not match format '%b'

### ISSUE THREAD

**Issue by FelixBuehler** [Ugluk4242/GEDCOM_MAPPING#1]
I'm getting the error above. I think it has to do with my birth/deaths containing an "EST", like "EST 1800"?

It happens when running the displacement_finder.py, when the scripts iterates through the places.

```
Traceback (most recent call last):
  File "/mnt/c/Users/Felix/Desktop/GEDCOM_MAPPING-main/displacement_finder.py", line 161, in <module>
    d2.append(time_modification(time_str))
  File "/mnt/c/Users/Felix/Desktop/GEDCOM_MAPPING-main/time_modification.py", line 41, in time_modification
    datetime_object = datetime.strptime(time_str[0:3], "%b")
  File "/usr/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'EST' does not match format '%b'
```

**Comment by Ugluk4242** [comment]
Hello!

The time_modification function serves the purpose of changing the dates in the gedcom files to a datetime object Python can understand. Several problematic cases are treated in the function, but it looks like you will need to add one here.

If you run time_modification in debug mode while giving it the date format for which you have an error, you should be able to find out which special case you need to add.

Maybe something like:

 if 'EST' in time_str:
     ...
